# Generated by Django 6.0.2 on 2026-02-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_dep', models.CharField(max_length=100)),
                ('adress_arr', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
