# Generated by Django 6.0.2 on 2026-02-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='tracking_number',
            field=models.CharField(default='FR1345', max_length=11),
        ),
    ]
