# Generated by Django 6.0.2 on 2026-02-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_parcel_tracking_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='tracking_number',
        ),
    ]
