# Generated by Django 6.0.2 on 2026-02-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_parcel_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='tracking_number',
            field=models.CharField(default='FR3563HD', max_length=11),
        ),
    ]
