# Generated by Django 6.0.2 on 2026-02-09 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_parcel_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
